### ISSUE TITLE
Ionic 5 + Angular 9 requires @angular/animations.

### ISSUE THREAD

**Issue by JeongJun-Lee** [jrquick17/ionic4-tooltips#10]
By manual, when BrowserAnimationsModule is added to app.module.ts, it also requires to install @angular/animations.
There is no error on installing except for upper thing, but unfortunately silently it doesn't work without any error. It is looks like not ready to Ionic5+Angular9.

**Comment by jrierab** [comment]
In Ionic 5, use also:
`npm install @angular/animations --save`

Then, there was a problem with the animation if the tooltip position was not specified. I simply added:
`positionV='bottom'`
... and then all tooltips began to work.

**Comment by jrquick17** [comment]
I have added @angular/animations to peer dependencies in v2.0.3. Thanks!
