### ISSUE TITLE
ng Compiling component takes long itme

### ISSUE THREAD

**Issue by almothafar** [jrquick17/ionic4-tooltips#18]
**Describe the bug**
This issue is not clear for me, it is simply taking long time to compile this component while using angular cli

**Screenshots**
![image](https://user-images.githubusercontent.com/13887564/121525822-757f7f00-ca01-11eb-8a06-8e1190e30ce3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser not related to browser
 - Version 2.0.2
- Angular Version: 12.0.x (latest)

**Comment by jrquick17** [comment]
I am not able reproduce this issue. If you can provide additional details to accurately reproduce then please reopen the issue.
